namespace AutoGeneratedSolution.Models.MetaData
{
	using Bases;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public class FactorInfoPaginationFilter : BaseSqlPaginationFilterParam
    {
		public override int? Skip { get; set; } = 0;
		public override int? Size { get; set; } = 10;

		
		public long? Id { get; set; }
		public string MultiText_Id { get; set; }
		public long? MinId { get; set; }
		public long? MaxId { get; set; }

		public string PhoneNumber { get; set; }
		public string MultiText_PhoneNumber { get; set; }

		public string ZipCode { get; set; }
		public string MultiText_ZipCode { get; set; }

		public string Address1 { get; set; }
		public string MultiText_Address1 { get; set; }

		public string Address2 { get; set; }
		public string MultiText_Address2 { get; set; }

		public bool? IsDeleted { get; set; }
		public string MultiText_IsDeleted { get; set; }

		public DateTimeOffset? ModifyDate { get; set; }
		public string MultiText_ModifyDate { get; set; }
		public DateTimeOffset? MinModifyDate { get; set; }
		public DateTimeOffset? MaxModifyDate { get; set; }

		public DateTimeOffset? SubmitDate { get; set; }
		public string MultiText_SubmitDate { get; set; }
		public DateTimeOffset? MinSubmitDate { get; set; }
		public DateTimeOffset? MaxSubmitDate { get; set; }


        public override string GetSpParams()
        {
            var result = "";

			result += SqlService.Convert(Skip) + ", ";
			result += SqlService.Convert(Size) + ", ";

            
			result += SqlService.Convert(Id) + ", ";
			result += SqlService.Convert(MultiText_Id) + ", ";
			result += SqlService.Convert(MinId) + ", ";
			result += SqlService.Convert(MaxId) + ",  ";

			result += SqlService.Convert(PhoneNumber) + ", ";

			result += SqlService.Convert(MultiText_PhoneNumber) + ",  ";


			result += SqlService.Convert(ZipCode) + ", ";

			result += SqlService.Convert(MultiText_ZipCode) + ",  ";


			result += SqlService.Convert(Address1) + ", ";

			result += SqlService.Convert(MultiText_Address1) + ",  ";


			result += SqlService.Convert(Address2) + ", ";

			result += SqlService.Convert(MultiText_Address2) + ",  ";


			result += SqlService.Convert(IsDeleted) + ", ";

			result += SqlService.Convert(MultiText_IsDeleted) + ",  ";


			result += SqlService.Convert(ModifyDate) + ", ";
			result += SqlService.Convert(MultiText_ModifyDate) + ", ";
			result += SqlService.Convert(MinModifyDate) + ", ";
			result += SqlService.Convert(MaxModifyDate) + ",  ";

			result += SqlService.Convert(SubmitDate) + ", ";
			result += SqlService.Convert(MultiText_SubmitDate) + ", ";
			result += SqlService.Convert(MinSubmitDate) + ", ";
			result += SqlService.Convert(MaxSubmitDate) + " ";


            return result;
        }
    }
}
